version: '3.8'

services:
  app:
    image: python:3.12-slim
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./server:/app
    depends_on:
      - qdrant
      - mongodb
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  qdrant_storage:
  mongodb_data:

networks:
  app-network:
    driver: bridge 